name: TransDSI
channels:
  - pytorch
  - conda-forge
  - defaults
  - pyg

dependencies:
  - pip=21.2.2
  - pytorch=2.3.0
  - h5py=3.5.0
  - matplotlib=3.5.0
  - numpy=1.21.2
  - pandas=1.3.4
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - seaborn=0.11.2
  - tqdm=4.62.3
  - xgboost
